### PR TITLE
Notes plugin: notes from data-notes attribute were not shown

### LINKED ISSUE #3476: Notes plugin: data-note does not work on slide-level
We have 2 different ways to specify notes: with `data-notes` attribute and also with separate tag `<aside class="notes"`. But former does not work for a slide(but works at fragment level btw)

Example:

```html
<section>
  notes will be shown
  <aside class="notes">slide-level notes</aside>
</section>
<section data-notes="slide-level notes">
  notes will NOT be shown
</section>
```

### PR DESCRIPTION
**Pull request by skyboyer**
Fixes #3476 : `data-notes` worked on fragment level, but not at slide level

### CODE REVIEW

File: plugin/notes/plugin.js [hunk 1]
```diff
@@ -146,7 +146,7 @@ const Plugin = () => {
 		}
 
 		// Look for notes defined in an aside element
-		if( notesElements ) {
+		if( notesElements && notesElements.length ) {
```
Comment (skyboyer) [inline plugin/notes/plugin.js:149]: `notesElements` is either `null`(if there is `.current-fragment`) or a list of elements(result of `slideElement.querySelectorAll( 'aside.notes' )`). 

So if we have a slide:
1. without fragments at all(so no `.current-fragment`)
2. with notes specified through `data-notes`

We did never see the notes because condition `if( notesElements )` was always `true` even though list was empty

**Comment by hakimel** [comment]
Good catch. Thanks for the fix.
